# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/huangcc/cmake/bin/cmake

# The command to remove a file.
RM = /home/huangcc/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huangcc/xurui/rtest/RDMA-Unified-Shared-Memory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huangcc/xurui/rtest/RDMA-Unified-Shared-Memory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/huangcc/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/huangcc/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huangcc/xurui/rtest/RDMA-Unified-Shared-Memory/CMakeFiles /home/huangcc/xurui/rtest/RDMA-Unified-Shared-Memory/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huangcc/xurui/rtest/RDMA-Unified-Shared-Memory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named index

# Build rule for target.
index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 index
.PHONY : index

# fast build rule for target.
index/fast:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/build
.PHONY : index/fast

#=============================================================================
# Target rules for targets named net

# Build rule for target.
net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net
.PHONY : net

# fast build rule for target.
net/fast:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/build
.PHONY : net/fast

src/client/tecli.o: src/client/tecli.cpp.o

.PHONY : src/client/tecli.o

# target to build an object file
src/client/tecli.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/tecli.cpp.o
.PHONY : src/client/tecli.cpp.o

src/client/tecli.i: src/client/tecli.cpp.i

.PHONY : src/client/tecli.i

# target to preprocess a source file
src/client/tecli.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/tecli.cpp.i
.PHONY : src/client/tecli.cpp.i

src/client/tecli.s: src/client/tecli.cpp.s

.PHONY : src/client/tecli.s

# target to generate assembly for a file
src/client/tecli.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/tecli.cpp.s
.PHONY : src/client/tecli.cpp.s

src/index/sc_skiplist.o: src/index/sc_skiplist.cpp.o

.PHONY : src/index/sc_skiplist.o

# target to build an object file
src/index/sc_skiplist.cpp.o:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/index/sc_skiplist.cpp.o
.PHONY : src/index/sc_skiplist.cpp.o

src/index/sc_skiplist.i: src/index/sc_skiplist.cpp.i

.PHONY : src/index/sc_skiplist.i

# target to preprocess a source file
src/index/sc_skiplist.cpp.i:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/index/sc_skiplist.cpp.i
.PHONY : src/index/sc_skiplist.cpp.i

src/index/sc_skiplist.s: src/index/sc_skiplist.cpp.s

.PHONY : src/index/sc_skiplist.s

# target to generate assembly for a file
src/index/sc_skiplist.cpp.s:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/index/sc_skiplist.cpp.s
.PHONY : src/index/sc_skiplist.cpp.s

src/index/skiplist.o: src/index/skiplist.cpp.o

.PHONY : src/index/skiplist.o

# target to build an object file
src/index/skiplist.cpp.o:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/index/skiplist.cpp.o
.PHONY : src/index/skiplist.cpp.o

src/index/skiplist.i: src/index/skiplist.cpp.i

.PHONY : src/index/skiplist.i

# target to preprocess a source file
src/index/skiplist.cpp.i:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/index/skiplist.cpp.i
.PHONY : src/index/skiplist.cpp.i

src/index/skiplist.s: src/index/skiplist.cpp.s

.PHONY : src/index/skiplist.s

# target to generate assembly for a file
src/index/skiplist.cpp.s:
	$(MAKE) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/index/skiplist.cpp.s
.PHONY : src/index/skiplist.cpp.s

src/net/BlockBitmap.o: src/net/BlockBitmap.cpp.o

.PHONY : src/net/BlockBitmap.o

# target to build an object file
src/net/BlockBitmap.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/BlockBitmap.cpp.o
.PHONY : src/net/BlockBitmap.cpp.o

src/net/BlockBitmap.i: src/net/BlockBitmap.cpp.i

.PHONY : src/net/BlockBitmap.i

# target to preprocess a source file
src/net/BlockBitmap.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/BlockBitmap.cpp.i
.PHONY : src/net/BlockBitmap.cpp.i

src/net/BlockBitmap.s: src/net/BlockBitmap.cpp.s

.PHONY : src/net/BlockBitmap.s

# target to generate assembly for a file
src/net/BlockBitmap.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/BlockBitmap.cpp.s
.PHONY : src/net/BlockBitmap.cpp.s

src/net/Configuration.o: src/net/Configuration.cpp.o

.PHONY : src/net/Configuration.o

# target to build an object file
src/net/Configuration.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/Configuration.cpp.o
.PHONY : src/net/Configuration.cpp.o

src/net/Configuration.i: src/net/Configuration.cpp.i

.PHONY : src/net/Configuration.i

# target to preprocess a source file
src/net/Configuration.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/Configuration.cpp.i
.PHONY : src/net/Configuration.cpp.i

src/net/Configuration.s: src/net/Configuration.cpp.s

.PHONY : src/net/Configuration.s

# target to generate assembly for a file
src/net/Configuration.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/Configuration.cpp.s
.PHONY : src/net/Configuration.cpp.s

src/net/MemoryManager.o: src/net/MemoryManager.cpp.o

.PHONY : src/net/MemoryManager.o

# target to build an object file
src/net/MemoryManager.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/MemoryManager.cpp.o
.PHONY : src/net/MemoryManager.cpp.o

src/net/MemoryManager.i: src/net/MemoryManager.cpp.i

.PHONY : src/net/MemoryManager.i

# target to preprocess a source file
src/net/MemoryManager.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/MemoryManager.cpp.i
.PHONY : src/net/MemoryManager.cpp.i

src/net/MemoryManager.s: src/net/MemoryManager.cpp.s

.PHONY : src/net/MemoryManager.s

# target to generate assembly for a file
src/net/MemoryManager.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/MemoryManager.cpp.s
.PHONY : src/net/MemoryManager.cpp.s

src/net/RdmaSocket.o: src/net/RdmaSocket.cpp.o

.PHONY : src/net/RdmaSocket.o

# target to build an object file
src/net/RdmaSocket.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/RdmaSocket.cpp.o
.PHONY : src/net/RdmaSocket.cpp.o

src/net/RdmaSocket.i: src/net/RdmaSocket.cpp.i

.PHONY : src/net/RdmaSocket.i

# target to preprocess a source file
src/net/RdmaSocket.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/RdmaSocket.cpp.i
.PHONY : src/net/RdmaSocket.cpp.i

src/net/RdmaSocket.s: src/net/RdmaSocket.cpp.s

.PHONY : src/net/RdmaSocket.s

# target to generate assembly for a file
src/net/RdmaSocket.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/RdmaSocket.cpp.s
.PHONY : src/net/RdmaSocket.cpp.s

src/net/client.o: src/net/client.cpp.o

.PHONY : src/net/client.o

# target to build an object file
src/net/client.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/client.cpp.o
.PHONY : src/net/client.cpp.o

src/net/client.i: src/net/client.cpp.i

.PHONY : src/net/client.i

# target to preprocess a source file
src/net/client.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/client.cpp.i
.PHONY : src/net/client.cpp.i

src/net/client.s: src/net/client.cpp.s

.PHONY : src/net/client.s

# target to generate assembly for a file
src/net/client.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/client.cpp.s
.PHONY : src/net/client.cpp.s

src/net/debug.o: src/net/debug.cpp.o

.PHONY : src/net/debug.o

# target to build an object file
src/net/debug.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/debug.cpp.o
.PHONY : src/net/debug.cpp.o

src/net/debug.i: src/net/debug.cpp.i

.PHONY : src/net/debug.i

# target to preprocess a source file
src/net/debug.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/debug.cpp.i
.PHONY : src/net/debug.cpp.i

src/net/debug.s: src/net/debug.cpp.s

.PHONY : src/net/debug.s

# target to generate assembly for a file
src/net/debug.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/debug.cpp.s
.PHONY : src/net/debug.cpp.s

src/net/server.o: src/net/server.cpp.o

.PHONY : src/net/server.o

# target to build an object file
src/net/server.cpp.o:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/server.cpp.o
.PHONY : src/net/server.cpp.o

src/net/server.i: src/net/server.cpp.i

.PHONY : src/net/server.i

# target to preprocess a source file
src/net/server.cpp.i:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/server.cpp.i
.PHONY : src/net/server.cpp.i

src/net/server.s: src/net/server.cpp.s

.PHONY : src/net/server.s

# target to generate assembly for a file
src/net/server.cpp.s:
	$(MAKE) -f CMakeFiles/net.dir/build.make CMakeFiles/net.dir/src/net/server.cpp.s
.PHONY : src/net/server.cpp.s

src/server/teser.o: src/server/teser.cpp.o

.PHONY : src/server/teser.o

# target to build an object file
src/server/teser.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/teser.cpp.o
.PHONY : src/server/teser.cpp.o

src/server/teser.i: src/server/teser.cpp.i

.PHONY : src/server/teser.i

# target to preprocess a source file
src/server/teser.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/teser.cpp.i
.PHONY : src/server/teser.cpp.i

src/server/teser.s: src/server/teser.cpp.s

.PHONY : src/server/teser.s

# target to generate assembly for a file
src/server/teser.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/teser.cpp.s
.PHONY : src/server/teser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... server"
	@echo "... rebuild_cache"
	@echo "... index"
	@echo "... net"
	@echo "... src/client/tecli.o"
	@echo "... src/client/tecli.i"
	@echo "... src/client/tecli.s"
	@echo "... src/index/sc_skiplist.o"
	@echo "... src/index/sc_skiplist.i"
	@echo "... src/index/sc_skiplist.s"
	@echo "... src/index/skiplist.o"
	@echo "... src/index/skiplist.i"
	@echo "... src/index/skiplist.s"
	@echo "... src/net/BlockBitmap.o"
	@echo "... src/net/BlockBitmap.i"
	@echo "... src/net/BlockBitmap.s"
	@echo "... src/net/Configuration.o"
	@echo "... src/net/Configuration.i"
	@echo "... src/net/Configuration.s"
	@echo "... src/net/MemoryManager.o"
	@echo "... src/net/MemoryManager.i"
	@echo "... src/net/MemoryManager.s"
	@echo "... src/net/RdmaSocket.o"
	@echo "... src/net/RdmaSocket.i"
	@echo "... src/net/RdmaSocket.s"
	@echo "... src/net/client.o"
	@echo "... src/net/client.i"
	@echo "... src/net/client.s"
	@echo "... src/net/debug.o"
	@echo "... src/net/debug.i"
	@echo "... src/net/debug.s"
	@echo "... src/net/server.o"
	@echo "... src/net/server.i"
	@echo "... src/net/server.s"
	@echo "... src/server/teser.o"
	@echo "... src/server/teser.i"
	@echo "... src/server/teser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

